# Generated by Django 5.2.3 on 2025-06-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coffee_System_App', '0002_drink_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='image',
        ),
    ]
