# Generated by Django 5.2.3 on 2025-06-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffee_System_App', '0003_remove_drink_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='drinks/'),
        ),
    ]
